apiVersion: v1
kind: Service
metadata:
  name: microservice
  namespace: microservice-namespace
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 32000
    - name: https
      port: 8081
      targetPort: 8081
      nodePort: 32001
  selector:
    app: microservice