apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice
  namespace: microservice-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice
  template:
    metadata:
      labels:
        app: microservice
    spec:
      containers:
        - name: microservice
          image: dotnetsample:1.0.0
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
          env:
            - name: RABBITMQ_HOST
              value: "rabbitmq.microservice-namespace.svc.cluster.local"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: "ASPNETCORE_HTTPS_PORTS"
              value: "8081"
            - name: "ASPNETCORE_HTTP_PORTS"
              value: "8080"
            - name: "ASPNETCORE_ENVIRONMENT"
              value: "Development"